### PR TITLE
added auth headers to socket connection

### PR DESCRIPTION
**Pull request by mukeshsolanki**
This is need as we need to be able to establish a connection to an authenticated socket url

### CODE REVIEW

**Comment by mukeshsolanki** [comment]
@LEECHHE can you take a look at the pr?

**Comment by LEECHHE** [comment]
https://github.com/LEECHHE/JavaPhoenixChannels/blob/191fab08057db0c4c37596b309c80383947fe16f/src/main/java/org/phoenixframework/channels/Socket.java#L175

You can use `Builder` for Socket and create you own `okhttpClient` which has headers. I'm sorry that it is not on README.md. I should have updated it but I've not expected someone create PL on my repo. :(

**Comment by mukeshsolanki** [comment]
That's alright thanks for the update

**Comment by Sompatbu** [comment]
Hello how to use the setHttpClient in current version?

I've try implemented through jitpack.io with latest version available(v0.3.0-alpha.2) and it's still not yet available.

Am I missing something?

**Pull request closed without merging**
